# Generated by Django 4.0.2 on 2022-03-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2),
        ),
    ]
