# Generated by Django 4.0.2 on 2022-05-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_office_type_listing_parking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='office_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='residential_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='warehouse_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('1', 'Office'), ('2', 'WareHouse'), ('3', 'Residential'), ('4', 'Factory'), ('5', 'Showroom')], default='Office', max_length=50),
        ),
    ]
