bedroom_choices = {
  '1':'Commercial Lease',
  '2':'Commercial Buy',
  '3':'Residential Buy',
  '4':'Residential Rent',
  '5':'Projects',
  '6':'6',
  '7':'7',
  '8':'8',
  '9':'9',
  '10':'10'
  }

price_choices = {
  '20000':'0 - ₹20,000',
  '500000':'₹50,000',
  '100000':'₹1 Lac',
  '200000':'₹1.5 Lacs',
  '200000':'₹2 Lacs',
  '1000000':'₹10 Lacs',
  '11000000':'₹10+ Lacs',
}

state_choices = {
        '0': 'All (Entire Chennai)',
        '1': 'Adambakkam',
        '2': 'Adyar',
        '3': 'Alwarpet',
        '4': 'Alwarthiru Nagar',
        '5': 'Ambattur',
        '6': 'Aminjikarai',
        '7': 'Anna Nagar',
        '8': 'Arumbakkam',
        '9': 'Ashok Nagar',
        '10': 'Ayanambakkam',
        '11': 'Ayanavaram',
        '12': 'Besant Nagar',
        '13': 'Chengalpattu',
        '14': 'Chetpet',
        '15': 'Choolaimedu',
        '16': 'Chrompet',
        '17': 'ECR',
        '18': 'Egmore',
        '19': 'Ekattuthangal',
        '20': 'Ennore',
        '21': 'Gopalapuram',
        '22': 'Guduvanchery',
        '23': 'Guindy',
        '24': 'Gummidipundi',
        '25': 'Kanchipuram',
        '26': 'Kilpauk',
        '27': 'KK Nagar',
        '28': 'Kodambakkam',
        '29': 'Kodungaiyur',
        '30': 'Kotturpuram',
        '31': 'Koyambedu',
        '32': 'Kundrathur',
        '33': 'Madhavaram',
        '34': 'Madipakkam',
        '35': 'Madurandagam',
        '36': 'Maduravoyal',
        '37': 'Manali',
        '38': 'Mandaveli',
        '39': 'Maraimalai Nagar',
        '40': 'Minjur',
        '41': 'Mount Road',
        '42': 'Mugappair',
        '43': 'Mylapore',
        '44': 'Nandambakkam',
        '45': 'Nandanam',
        '46': 'Nanganallur',
        '47': 'Nungambakkam',
        '48': 'OMR',
        '49': 'Oragadam',
        '50': 'Padappai',
        '51': 'Pallavaram',
        '52': 'Pallikaranai',
        '53': 'Parrys',
        '54': 'Perambur',
        '55': 'Periamet',
        '56': 'PH Road',
        '57': 'Ponneri',
        '58': 'Poonamallee',
        '59': 'Porur',
        '60': 'Purasaiwakkam',
        '61': 'RA Puram',
        '62': 'Redhills',
        '63': 'Royapettah',
        '64': 'Royapuram',
        '65': 'Saidapet',
        '66': 'Saligramam',
        '67': 'Sriperumbathur',
        '68': 'T Nagar',
        '69': 'Tambaram',
        '70': 'Thiruvallur',
        '71': 'Thiruvanmiyur',
        '72': 'Thiruvattriyur',
        '73': 'Thousand Lights',
        '74': 'Triplicane',
        '75': 'Vadapalani',
        '76': 'Valasaravakkam',
        '77': 'Vanagaram',
        '78': 'Velachery',
        '79': 'Villivakkam',
        '80': 'Virugambakkam',
        '81': 'Saligramam',
        '82': 'Sriperumbathur',
        '83': 'Washermanpet West',
        '84': 'Tambaram',
        '85': 'Thiruvallur',
        '86': 'Anna Nagar',
        '87': 'West Mambalam',
}